In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('teste1.csv')

In [3]:
df.head(10)

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Rio Branco,1200401,2020-03-17,202012,413418,407319,False,False,3,0.72566,2020-03-17,0.0,0,1,city,AC,3,0
1,NaN,12,2020-03-17,202012,894470,881935,False,False,3,0.33539,2020-03-17,0.0,0,1,state,AC,3,0
2,Rio Branco,1200401,2020-03-18,202012,413418,407319,False,False,3,0.72566,2020-03-18,0.0,0,2,city,AC,0,0
3,NaN,12,2020-03-18,202012,894470,881935,False,False,3,0.33539,2020-03-18,0.0,0,2,state,AC,0,0
4,Rio Branco,1200401,2020-03-19,202012,413418,407319,False,False,4,0.96754,2020-03-19,0.0,0,3,city,AC,1,0
5,NaN,12,2020-03-19,202012,894470,881935,False,False,4,0.44719,2020-03-19,0.0,0,3,state,AC,1,0
6,Rio Branco,1200401,2020-03-20,202012,413418,407319,False,False,7,1.69320,2020-03-20,0.0,0,4,city,AC,3,0
7,NaN,12,2020-03-20,202012,894470,881935,False,False,7,0.78259,2020-03-20,0.0,0,4,state,AC,3,0
8,Rio Branco,1200401,2020-03-21,202012,413418,407319,False,False,11,2.66075,2020-03-21,0.0,0,5,city,AC,4,0
9,NaN,12,2020-03-21,202012,894470,881935,False,False,11,1.22978,2020-03-21,0.0,0,5,state,AC,4,0

In [4]:
df.dropna(inplace=True)

In [6]:
df['city'].unique()

array(['Rio Branco', 'AcrelÃ¢ndia', 'Porto Acre', 'PlÃ¡cido de Castro',
       'Bujari', 'Cruzeiro do Sul', 'Senador Guiomard', 'MÃ¢ncio Lima',
       'Xapuri', 'Assis Brasil', 'FeijÃ³', 'TarauacÃ¡', 'Sena Madureira',
       'EpitaciolÃ¢ndia', 'Capixaba', 'Santa Rosa do Purus', 'BrasilÃ©ia',
       'Marechal Thaumaturgo', 'Rodrigues Alves', 'Manoel Urbano',
       'Porto Walter', 'JordÃ£o'], dtype=object)

In [7]:
df['city'].replace({'AcrelÃ¢ndia' : 'Acrelândia', 'PlÃ¡cido de Castro' : 'Plácido de Castro', 'MÃ¢ncio Lima' : 'Mâncio Lima', 'FeijÃ³' : 'Feijó', 'TarauacÃ¡' : 'Tarauacá', 'EpitaciolÃ¢ndia' : 'Epitaciolândia', 'BrasilÃ©ia' : 'Brasiléia', 'JordÃ£o' : 'Jordão'}, inplace=True)

In [8]:
df['city'].unique()

array(['Rio Branco', 'Acrelândia', 'Porto Acre', 'Plácido de Castro',
       'Bujari', 'Cruzeiro do Sul', 'Senador Guiomard', 'Mâncio Lima',
       'Xapuri', 'Assis Brasil', 'Feijó', 'Tarauacá', 'Sena Madureira',
       'Epitaciolândia', 'Capixaba', 'Santa Rosa do Purus', 'Brasiléia',
       'Marechal Thaumaturgo', 'Rodrigues Alves', 'Manoel Urbano',
       'Porto Walter', 'Jordão'], dtype=object)

In [10]:
df['ano'] = df["date"].str[:4].astype(object)
df['mes'] = df["date"].str[5:7].astype(object)

In [11]:
df['mes'].replace({'03':'Março', '04':'Abril', '05':'Maio', '06':'Junho'}, inplace=True)

In [12]:
df.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths,ano,mes
0,Rio Branco,1200401,2020-03-17,202012,413418,407319,False,False,3,0.72566,2020-03-17,0.0,0,1,city,AC,3,0,2020,Março
2,Rio Branco,1200401,2020-03-18,202012,413418,407319,False,False,3,0.72566,2020-03-18,0.0,0,2,city,AC,0,0,2020,Março
4,Rio Branco,1200401,2020-03-19,202012,413418,407319,False,False,4,0.96754,2020-03-19,0.0,0,3,city,AC,1,0,2020,Março
6,Rio Branco,1200401,2020-03-20,202012,413418,407319,False,False,7,1.69320,2020-03-20,0.0,0,4,city,AC,3,0,2020,Março
8,Rio Branco,1200401,2020-03-21,202012,413418,407319,False,False,11,2.66075,2020-03-21,0.0,0,5,city,AC,4,0,2020,Março

In [15]:
df1 = pd.read_csv('transito_dados.csv')

In [16]:
df1.head()

,_id,amparo_legal,ano,descricao_infracao,escopo_autuacao,mes,quantidade_autos,uf
0,6407641b305a576376e6f33c,Lei 9503/97 Lei 10561/02 Res. CONTRAN nº 210/0...,2021,Transitar com o veículo excedendo a CMT em até...,CMT - Capacidade Máxima de Tração,JANEIRO,1,ES
1,6407641b305a576376e6f33d,Lei 9503/97 Lei 10561/02 Res. CONTRAN nº 210/0...,2021,Transitar com o veículo excedendo a CMT acima ...,CMT - Capacidade Máxima de Tração,JANEIRO,2,MG
2,6407641b305a576376e6f33e,Lei 9503/97 Lei 10561/02 Res. CONTRAN nº 210/0...,2021,Transitar com o veículo excedendo a CMT acima ...,CMT - Capacidade Máxima de Tração,JANEIRO,1,MS
3,6407641b305a576376e6f33f,Lei 9503/97 Lei 10561/02 Res. CONTRAN nº 210/0...,2021,Transitar com o veículo excedendo a CMT entre ...,CMT - Capacidade Máxima de Tração,JANEIRO,2,RJ
4,6407641b305a576376e6f340,Lei 9503/97 Lei 10561/02 Res. CONTRAN nº 210/0...,2021,Transitar com o veículo excedendo a CMT acima ...,CMT - Capacidade Máxima de Tração,JANEIRO,3,RJ

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _id                 970 non-null    object
 1   amparo_legal        959 non-null    object
 2   ano                 970 non-null    int64
 3   descricao_infracao  970 non-null    object
 4   escopo_autuacao     970 non-null    object
 5   mes                 970 non-null    object
 6   quantidade_autos    970 non-null    int64
 7   uf                  970 non-null    object
dtypes: int64(2), object(6)
memory usage: 60.8+ KB

In [18]:
df3 =  pd.concat([df, df1])

In [19]:
df3.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,...,new_confirmed,new_deaths,ano,mes,_id,amparo_legal,descricao_infracao,escopo_autuacao,quantidade_autos,uf
0,Rio Branco,1200401.0,2020-03-17,202012.0,413418.0,407319.0,False,False,3.0,0.72566,...,3.0,0.0,2020,Março,NaN,NaN,NaN,NaN,NaN,NaN
2,Rio Branco,1200401.0,2020-03-18,202012.0,413418.0,407319.0,False,False,3.0,0.72566,...,0.0,0.0,2020,Março,NaN,NaN,NaN,NaN,NaN,NaN
4,Rio Branco,1200401.0,2020-03-19,202012.0,413418.0,407319.0,False,False,4.0,0.96754,...,1.0,0.0,2020,Março,NaN,NaN,NaN,NaN,NaN,NaN
6,Rio Branco,1200401.0,2020-03-20,202012.0,413418.0,407319.0,False,False,7.0,1.69320,...,3.0,0.0,2020,Março,NaN,NaN,NaN,NaN,NaN,NaN
8,Rio Branco,1200401.0,2020-03-21,202012.0,413418.0,407319.0,False,False,11.0,2.66075,...,4.0,0.0,2020,Março,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df3.fillna (0, inplace=True)

In [21]:
df3.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,...,new_confirmed,new_deaths,ano,mes,_id,amparo_legal,descricao_infracao,escopo_autuacao,quantidade_autos,uf
0,Rio Branco,1200401.0,2020-03-17,202012.0,413418.0,407319.0,False,False,3.0,0.72566,...,3.0,0.0,2020,Março,0,0,0,0,0.0,0
2,Rio Branco,1200401.0,2020-03-18,202012.0,413418.0,407319.0,False,False,3.0,0.72566,...,0.0,0.0,2020,Março,0,0,0,0,0.0,0
4,Rio Branco,1200401.0,2020-03-19,202012.0,413418.0,407319.0,False,False,4.0,0.96754,...,1.0,0.0,2020,Março,0,0,0,0,0.0,0
6,Rio Branco,1200401.0,2020-03-20,202012.0,413418.0,407319.0,False,False,7.0,1.69320,...,3.0,0.0,2020,Março,0,0,0,0,0.0,0
8,Rio Branco,1200401.0,2020-03-21,202012.0,413418.0,407319.0,False,False,11.0,2.66075,...,4.0,0.0,2020,Março,0,0,0,0,0.0,0

In [22]:
df3.to_csv('dados_finais.csv', index=0)